export default {
  'currency': [
    {
      id: 1,
      created_date: 1602001134280,
      modified_date: 1602001134280,
      currency_type: null,
      currency: "BTC",
      symbol: "₿",
      quoting_precision: 1,
      assets_precision: 1,
      display_precision: 5,
      minimum_withdrawal: 0.01,
      withdrawal_fee: 0.00001,
      minimum_order_quantity: 0.000001,
      minimum_fee: 0.00001,
      num: 1,
      minor_unit: 1,
      compute_units: 1,
      visible_units: 1,
      depositable: true,
      withdrawable: true,
      root_currency: null,
      qws_enabled: false,
      has_memo: false,
      active: false,
      deleted: false
    },
    {
      id: 2,
      created_date: 1602001134319,
      modified_date: 1602001134319,
      currency_type: null,
      currency: "ETH",
      symbol: "Ξ",
      quoting_precision: 1,
      assets_precision: 1,
      display_precision: 2,
      minimum_withdrawal: 0.1,
      withdrawal_fee: 0.001,
      minimum_order_quantity: 0.001,
      minimum_fee: 0.00001,
      num: 1,
      minor_unit: 1,
      compute_units: 1,
      visible_units: 1,
      depositable: true,
      withdrawable: true,
      root_currency: null,
      qws_enabled: false,
      has_memo: false,
      active:false,
      deleted: false
    },
    {
      id: 3,
      created_date: 1602001134329,
      modified_date: 1602001134329,
      currency_type: "FIAT",
      currency: "VND",
      symbol: "₫",
      quoting_precision: 1,
      assets_precision: 1,
      display_precision: 0,
      minimum_withdrawal: 100000,
      withdrawal_fee: 5000,
      minimum_order_quantity: 10000,
      minimum_fee: 1000,
      num: 1,
      minor_unit: 1,
      compute_units: 1,
      visible_units: 1,
      depositable: true,
      withdrawable: true,
      root_currency: null,
      qws_enabled: false,
      has_memo: false,
      active: false,
      deleted: false
    },
    {
      id: 4,
      created_date: 1602001134336,
      modified_date: 1602001134336,
      currency_type: "FIAT",
      currency: "USD",
      symbol: "$",
      quoting_precision: 1,
      assets_precision: 1,
      display_precision: 0,
      minimum_withdrawal: 50,
      withdrawal_fee: 2,
      minimum_order_quantity: 10,
      minimum_fee: 1,
      num: 1,
      minor_unit: 1,
      compute_units: 1,
      visible_units: 1,
      depositable: true,
      withdrawable: true,
      root_currency: null,
      qws_enabled: false,
      has_memo: false,
      active: false,
      deleted: false
    }
  ],
  'users': [
    {
      id: 1,
      created_date: 1602001134336,
      modified_date: 1602001134336,
      is_active: true,
      is_deleted: false,
      avatar:null,
      confirm: true,
      confirm_token: "",
      confirm_token_sent_at: 1602001134336,
      currency: "VND",
      first_name: "Quang",
      last_name: "Nguyen",
      last_sign_in_at: null,
      last_sign_in_io: "",
      locked_at: null,
      password: "quang123",
      reset_password_sent_at: null,
      reset_password_token: "",
      status: "",
      tfa_secret_key:"abcd",
      un_lock_token: null,
    },
    {
     id: 2,
     created_date: 1602001134336,
     modified_date: 1602001134336,
     is_active: true,
     is_deleted: false,
     avatar:null,
     confirm: true,
     confirm_token: "",
     confirm_token_sent_at: 1602001134336,
     currency: "USD",
     first_name: "Quang 1",
     last_name: "Nguyen 1",
     last_sign_in_at: null,
     last_sign_in_io: "",
     locked_at: null,
     password: "quang123",
     reset_password_sent_at: null,
     reset_password_token: "",
     status: "",
     tfa_secret_key:"abcd",
     un_lock_token: null,
    }
  ],
  'accounts': [
    {
      id: 1,
      created_date: 1602001134336,
     modified_date: 1602001134336, 
     is_active: true,
     is_deleted: false,
     modified_data: null,
     currency: "VND",
     user_id: 1,
     created_by_id: 1,
     updated_by_id: 1
    },
    {
      id: 1,
      created_date: 1602001134336,
     modified_date: 1602001134336, 
     is_active: true,
     is_deleted: false,
     modified_data: null,
     currency: "VND",
     user_id: 1,
     created_by_id: 1,
     updated_by_id: 1
    }
  ],
  'admin_users': [
    {
      id:1,
      created_date: 1602001134336,
      modified_date: 1602001134336,  
      active: true,
      deleted: false,
      avatar: null,
      email: "quangnt123@gmail.cpm",
      first_name: "admin",
      last_name: "admin",
      password: "admin",
      status: "",
      enable_tfa: true,
      tfa_secret_key: "abcd"
    },
    {
      id:2,
      created_date: 1602001134336,
      modified_date: 1602001134336,  
      active: true,
      deleted: false,
      avatar: null,
      email: "quangnt@gmail.com",
      first_name: "admin1",
      last_name: "admin1",
      password: "admin",
      status: "",
      enable_tfa: true,
      tfa_secret_key: "abcd"
    }, 
  ],
  'admin_user_roles': [
    {role_id: 1, admin_user_id: 1},
    {role_id: 2, admin_user_id: 2}
  ],
  'roles': [
    {id: 1, name: "super admin"}, 
    {id: 2, name: "admin"},
  ],

}